export const ritualCatalog = [
  {
    id: 'breath-2min-reset',
    title: '2-minute breath reset',
    minutes: 2,
    type: 'breath',
    tags: ['calming', 'no-mat', 'quiet', 'anytime'],
    intensity: 'gentle',
    instructions: 'Inhale for 4, exhale for 6. Slow, easy, and steady.',
    media: {
      kind: 'audio',
      access: 'free',
      provider: 'freeCdn',
      key: 'breath/breath-2min-reset.mp3',
    },
  },
  {
    id: 'gratitude-3min-note',
    title: '3-minute gratitude + intention',
    minutes: 3,
    type: 'note',
    tags: ['grounding', 'anytime', 'quiet'],
    intensity: 'gentle',
    instructions: 'Write one thing you appreciate, one thing you need today.',
  },
  {
    id: 'warm-water-morning',
    title: 'Warm water + gentle start',
    minutes: 4,
    type: 'habit',
    tags: ['morning', 'digestion', 'no-mat'],
    intensity: 'gentle',
    instructions: 'Sip warm water, pause, and take three calm breaths.',
  },
  {
    id: 'neck-shoulders-5min',
    title: '5-minute neck + shoulders',
    minutes: 5,
    type: 'yoga',
    tags: ['neck', 'shoulders', 'no-mat', 'quiet'],
    intensity: 'gentle',
    instructions: 'Slow circles, soft stretches, no strain.',
  },
  {
    id: 'kid-friendly-breath',
    title: '3-minute kid-friendly breath',
    minutes: 3,
    type: 'breath',
    tags: ['kid-friendly', 'no-mat', 'anytime'],
    intensity: 'gentle',
    instructions: 'Smell the flower, blow the candle. Repeat slowly.',
  },
  {
    id: 'morning-mobility-10',
    title: '10-minute morning mobility',
    minutes: 10,
    type: 'yoga',
    tags: ['morning', 'back', 'hips'],
    intensity: 'steady',
    instructions: 'Cat-cow, low lunge, gentle twists.',
    media: {
      kind: 'video',
      access: 'free',
      provider: 'freeCdn',
      key: 'yoga/morning-mobility-10.mp4',
      posterKey: 'posters/morning-mobility-10.jpg',
    },
  },
  {
    id: 'spine-shoulders-7',
    title: '7-minute spine + shoulders',
    minutes: 7,
    type: 'yoga',
    tags: ['back', 'shoulders', 'desk'],
    intensity: 'gentle',
    instructions: 'Move slowly, pause where it feels good.',
  },
  {
    id: 'evening-wind-down-12',
    title: '12-minute calm-down after the day',
    minutes: 12,
    type: 'meditation',
    tags: ['evening', 'sleep', 'quiet'],
    intensity: 'gentle',
    instructions: 'Body scan + soft breath counting.',
    media: {
      kind: 'audio',
      access: 'free',
      provider: 'freeCdn',
      key: 'meditations/evening-wind-down-12.mp3',
    },
  },
  {
    id: 'steady-energy-15',
    title: '15-minute steady energy flow',
    minutes: 15,
    type: 'yoga',
    tags: ['midday', 'energy'],
    intensity: 'steady',
    instructions: 'Simple flow, no rush. Keep it easy.',
    media: {
      kind: 'video',
      access: 'paid',
      provider: 'paidCdn',
      key: 'yoga/steady-energy-15.mp4',
      posterKey: 'posters/steady-energy-15.jpg',
    },
  },
  {
    id: 'focus-5min',
    title: '5-minute focus reset',
    minutes: 5,
    type: 'meditation',
    tags: ['midday', 'focus', 'quiet'],
    intensity: 'gentle',
    instructions: 'Count 10 breaths, restart if you drift.',
  },
  {
    id: 'hips-10',
    title: '10-minute hips + low back care',
    minutes: 10,
    type: 'yoga',
    tags: ['hips', 'back', 'evening'],
    intensity: 'gentle',
    instructions: 'Long holds, soft edges, no forcing.',
  },
  {
    id: 'standing-reset-6',
    title: '6-minute standing reset',
    minutes: 6,
    type: 'yoga',
    tags: ['no-mat', 'anytime', 'balance'],
    intensity: 'gentle',
    instructions: 'Mountain, side stretch, gentle fold.',
  },
  {
    id: 'quiet-sit-8',
    title: '8-minute quiet sit',
    minutes: 8,
    type: 'meditation',
    tags: ['quiet', 'evening', 'calming'],
    intensity: 'gentle',
    instructions: 'Let the breath be natural. Notice the exhale.',
    media: {
      kind: 'audio',
      access: 'paid',
      provider: 'paidCdn',
      key: 'meditations/quiet-sit-8.mp3',
    },
  },
  {
    id: 'vata-grounding-9',
    title: '9-minute grounding flow',
    minutes: 9,
    type: 'yoga',
    tags: ['grounding', 'vata', 'morning'],
    intensity: 'gentle',
    instructions: 'Slow pace, longer holds, steady breath.',
    media: {
      kind: 'video',
      access: 'free',
      provider: 'freeCdn',
      key: 'yoga/vata-grounding-9.mp4',
      posterKey: 'posters/vata-grounding-9.jpg',
    },
  },
  {
    id: 'pitta-cooling-7',
    title: '7-minute cooling breath',
    minutes: 7,
    type: 'breath',
    tags: ['cooling', 'pitta', 'midday'],
    intensity: 'gentle',
    instructions: 'Slow exhale focus, soften the jaw.',
  },
  {
    id: 'kapha-lift-8',
    title: '8-minute gentle lift',
    minutes: 8,
    type: 'yoga',
    tags: ['kapha', 'energy', 'morning'],
    intensity: 'steady',
    instructions: 'Simple flow with light effort.',
  },
  {
    id: 'sleepy-3',
    title: '3-minute sleepy eyes',
    minutes: 3,
    type: 'habit',
    tags: ['sleep', 'evening', 'quiet'],
    intensity: 'gentle',
    instructions: 'Warm washcloth on eyes, breathe slowly.',
  },
  {
    id: 'journal-5',
    title: '5-minute gentle journal',
    minutes: 5,
    type: 'note',
    tags: ['quiet', 'evening', 'anytime'],
    intensity: 'gentle',
    instructions: 'One page or five lines — either counts.',
  },
  {
    id: 'digestive-walk-10',
    title: '10-minute digestive walk',
    minutes: 10,
    type: 'habit',
    tags: ['digestion', 'after-meal', 'anytime'],
    intensity: 'gentle',
    instructions: 'Easy pace, nasal breathing if comfortable.',
  },
  {
    id: 'box-breath-4',
    title: '4-minute box breath',
    minutes: 4,
    type: 'breath',
    tags: ['calming', 'focus', 'no-mat'],
    intensity: 'gentle',
    instructions: '4 in, 4 hold, 4 out, 4 hold.',
  },
  {
    id: 'midday-shoulders-6',
    title: '6-minute desk shoulders reset',
    minutes: 6,
    type: 'yoga',
    tags: ['desk', 'shoulders', 'no-mat'],
    intensity: 'gentle',
    instructions: 'Roll, stretch, and breathe. Keep it soft.',
  },
  {
    id: 'kind-to-knees-7',
    title: '7-minute kind-to-knees flow',
    minutes: 7,
    type: 'yoga',
    tags: ['knees', 'gentle', 'evening'],
    intensity: 'gentle',
    instructions: 'Support with a pillow or folded blanket.',
  },
  {
    id: 'tea-pause-5',
    title: '5-minute tea pause',
    minutes: 5,
    type: 'habit',
    tags: ['quiet', 'anytime', 'calming'],
    intensity: 'gentle',
    instructions: 'Make tea, sit, sip slowly.',
  },
  {
    id: 'flow-sun-a-7',
    title: '7-minute Sun Salutation A (easy pace)',
    minutes: 7,
    type: 'yoga',
    tags: ['morning', 'energy', 'classic', 'mat'],
    intensity: 'steady',
    instructions: 'Skip anything that doesn’t feel good today. Modify freely.',
    media: {
      kind: 'video',
      access: 'free',
      provider: 'freeCdn',
      key: 'yoga/flow-sun-a-7.mp4',
      posterKey: 'posters/flow-sun-a-7.jpg',
    },
  },
  {
    id: 'sunlight-2',
    title: '2-minute sunlight reset',
    minutes: 2,
    type: 'habit',
    tags: ['morning', 'anytime', 'energy'],
    intensity: 'gentle',
    instructions: 'Step outside, face the light, breathe.',
  },
  {
    id: 'breath-5min-slow',
    title: '5-minute slow exhale',
    minutes: 5,
    type: 'breath',
    tags: ['calming', 'sleep', 'quiet'],
    intensity: 'gentle',
    instructions: 'Exhale a little longer than you inhale.',
  },
];
