import { CDN_BASE } from '../../../lib/media/cdn';

const crystalBase = `${CDN_BASE}/icons/chakra-crystal-system/svg`;

export const CHAKRAS = [
  {
    id: 'root',
    name: 'Root Chakra',
    sanskrit: 'Muladhara',
    glow: '#E57373',
    svg: `${crystalBase}/root.svg`,
    governs: ['Safety', 'stability', 'basic needs'],
    imbalance: ['Anxiety about security', 'restlessness', 'difficulty settling'],
    practices: ['Regular meals', 'time outdoors', 'simple routines that repeat daily'],
    tone: 'This is not about fear — it is about support. When the foundation is steady, everything else costs less effort.',
  },
  {
    id: 'sacral',
    name: 'Sacral Chakra',
    sanskrit: 'Svadhisthana',
    glow: '#FFB74D',
    svg: `${crystalBase}/sacral.svg`,
    governs: ['Emotion', 'creativity', 'adaptability'],
    imbalance: ['Emotional flatness', 'over-attachment', 'resistance to change'],
    practices: ['Unstructured creative time', 'fluid movement', 'allowing pleasure without justification'],
    tone: 'Balance here is not indulgence. It is flexibility — the ability to respond without force.',
  },
  {
    id: 'solar',
    name: 'Solar Plexus Chakra',
    sanskrit: 'Manipura',
    glow: '#FFF176',
    svg: `${crystalBase}/solar.svg`,
    governs: ['Energy', 'digestion', 'personal agency'],
    imbalance: ['Burnout', 'irritability', 'difficulty pacing effort'],
    practices: ['Consistent meal timing', 'short periods of focused effort', 'rest before exhaustion appears'],
    tone: 'This center does not ask for intensity — it asks for regulation.',
  },
  {
    id: 'heart',
    name: 'Heart Chakra',
    sanskrit: 'Anahata',
    glow: '#81C784',
    svg: `${crystalBase}/heart.svg`,
    governs: ['Connection', 'compassion', 'emotional balance'],
    imbalance: ['Withdrawal', 'over-giving', 'emotional fatigue'],
    practices: ['Slow nasal breathing', 'balanced giving and receiving', 'quiet appreciation without analysis'],
    tone: 'This is not about openness at all costs. It is about sustainable connection.',
  },
  {
    id: 'throat',
    name: 'Throat Chakra',
    sanskrit: 'Vishuddha',
    glow: '#64B5F6',
    svg: `${crystalBase}/throat.svg`,
    governs: ['Expression', 'communication', 'clarity'],
    imbalance: ['Holding things in', 'speaking without grounding', 'misalignment between thought and speech'],
    practices: ['Writing before speaking', 'pausing before responding', 'clear, simple language'],
    tone: 'Clarity is often restraint, not volume.',
  },
  {
    id: 'third-eye',
    name: 'Third Eye Chakra',
    sanskrit: 'Ajna',
    glow: '#9575CD',
    svg: `${crystalBase}/third-eye.svg`,
    governs: ['Perception', 'insight', 'pattern recognition'],
    imbalance: ['Overthinking', 'mental fatigue', 'difficulty trusting judgment'],
    practices: ['Reducing input', 'quiet reflection', 'letting decisions settle before acting'],
    tone: 'Insight improves when noise decreases.',
  },
  {
    id: 'crown',
    name: 'Crown Chakra',
    sanskrit: 'Sahasrara',
    glow: '#BA68C8',
    svg: `${crystalBase}/crown.svg`,
    governs: ['Perspective', 'meaning', 'integration'],
    imbalance: ['Disconnection', 'cynicism', 'feeling unmoored'],
    practices: ['Stillness without expectation', 'time away from goals', 'remembering context beyond the self'],
    tone: 'This is not transcendence — it is orientation.',
  },
];

export const DOSHAS = [
  { id: 'vata', label: 'Vata', color: '#546E7A' },
  { id: 'pitta', label: 'Pitta', color: '#C62828' },
  { id: 'kapha', label: 'Kapha', color: '#6D4C41' },
];

export const RITUALS = [
  { id: 'warm-meal', label: 'Warm meal', supports: ['root'], biases: ['kapha'] },
  { id: 'short-walk', label: 'Short walk outside', supports: ['root'], biases: ['kapha'] },
  { id: 'tidy-space', label: 'Tidy one small area', supports: ['root'], biases: ['kapha'] },
  { id: 'creative-pause', label: 'Creative pause (write, sketch, hum)', supports: ['sacral'], biases: ['vata'] },
  { id: 'fluid-move', label: 'Five minutes of unstructured movement', supports: ['sacral'], biases: ['vata'] },
  { id: 'warm-shower', label: 'Warm shower or bath', supports: ['sacral'], biases: ['vata', 'kapha'] },
  { id: 'screenless-meal', label: 'Eat without screens', supports: ['solar'], biases: ['pitta'] },
  { id: 'focused-task', label: 'One focused task, then stop', supports: ['solar'], biases: ['pitta'] },
  { id: 'core-breath', label: 'Gentle core breathing', supports: ['solar'], biases: ['pitta'] },
  { id: 'nasal-breath', label: 'Slow nasal breathing (2 minutes)', supports: ['heart'], biases: ['vata'] },
  { id: 'appreciation', label: 'Write one line of appreciation', supports: ['heart'], biases: ['kapha'] },
  { id: 'chest-open', label: 'Gentle chest opening stretch', supports: ['heart'], biases: ['kapha'] },
  { id: 'write-before', label: 'Write before speaking', supports: ['throat'], biases: ['vata'] },
  { id: 'pause-response', label: 'Pause before responding', supports: ['throat'], biases: ['pitta'] },
  { id: 'read-aloud', label: 'Read something calming aloud', supports: ['throat'], biases: ['vata'] },
  { id: 'reduce-input', label: 'Reduce inputs for 10 minutes', supports: ['third-eye'], biases: ['vata'] },
  { id: 'quiet-sit', label: 'Sit quietly with eyes closed', supports: ['third-eye'], biases: ['vata'] },
  { id: 'step-away', label: 'Step away from decisions briefly', supports: ['third-eye'], biases: ['kapha'] },
  { id: 'stillness', label: 'Stillness without intent', supports: ['crown'], biases: ['vata'] },
  { id: 'outdoors', label: 'Time outdoors without headphones', supports: ['crown'], biases: ['vata'] },
  { id: 'big-picture', label: 'Brief reflection on the larger picture', supports: ['crown'], biases: ['vata'] },
];
